# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  workflow_dispatch:
    inputs:
      # What arguments should be passed to "R CMD check"?
      build_args:
        description: 'Value for build_args'
        type: string
        default: c("--no-manual", "--no-build-vignettes")
      error-on:
        description: 'Value for error-on'
        type: string
        default: '"error"'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Echo inputs
        run: |
          echo "build_args: ${{ github.event.inputs.build_args }}"
          echo "error-on: ${{ github.event.inputs.error-on }}"

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: c('--no-examples', '--no-tests', '--no-manual', '--ignore-vignettes', '--as-cran')
          build_args: ${{ github.event.inputs.build_args }}
          error-on:  ${{ github.event.inputs.error-on }}
          #build_args: "\"--no-build-vignettes\""
          #error-on:  c("warning")
